version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-dev
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - database
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  database:
    image: postgres:13
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"  # Porta padrão liberada no host
    env_file:
      - .env
    environment:
      - TZ=America/Sao_Paulo
      - PGTZ=America/Sao_Paulo  # Opcional, reforça timezone para Postgres >= 12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:

