version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-prod
    container_name: frontend-prod
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-prod
    expose:
      - "3000"
    env_file:
      - .env.prod
    depends_on:
      - database
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  database:
    image: postgres:13
    container_name: postgres-prod
    restart: unless-stopped
    expose:
      - "5432"
    env_file:
      - .env.prod
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:

